# Use the official lightweight Node.js 18 image
FROM node:18-alpine

# Set the working directory
WORKDIR /usr/src/app

# Install dependencies
COPY package*.json ./
RUN npm install

# Copy the rest of the files
COPY . .

# Build the project
RUN npm run build

# Set the command to run the project
CMD ["npm", "start"]
